export const properties = [
  {
    id: 1,
    title: "Luxury Villa",
    location: "Gurugram",
    price: "₹85,00,000",
    image: "/images/property1.jpg",
    beds: 4,
    baths: 3,
    area: "2200 sqft",
    featured: true,
  },
  {
    id: 2,
    title: "Modern Apartment",
    location: "Sohna",
    price: "₹62,00,000",
    image: "/images/property2.jpg",
    beds: 3,
    baths: 2,
    area: "1600 sqft",
    featured: true,
  },
  {
    id: 3,
    title: "Residential Plot",
    location: "Bhondsi",
    price: "₹45,00,000",
    image: "/images/property3.jpg",
    beds: 0,
    baths: 0,
    area: "180 Sq.Yd",
    featured: true,
  },
  {
    id: 4,
    title: "Commercial Space",
    location: "MG Road",
    price: "₹1.25 Cr",
    image: "/images/property4.jpg",
    beds: 0,
    baths: 2,
    area: "3200 sqft",
    featured: true,
  },
];