export const properties = [
  {
    id: 1,
    title: "Residential Plot in Sohna",
    price: "₹ 45.00 Lakh",
    location: "Sohna, Gurugram",
    image: "/images/property1.jpg",
    type: "Featured",
    beds: 2,
    baths: 1,
    area: "130 Sq Yd",
    verified: true,
    amenities: [
      "24×7 Security",
      "Swimming Pool",
      "Gymnasium",
      "Children's Play Area",
      "Club House",
      "Power Backup",
      "Lift",
      "Visitor Parking",
      "Jogging Track",
      "CCTV Surveillance",
      "Landscaped Garden",
      "Rain Water Harvesting",
    ],
  },
  {
    id: 2,
    title: "3 BHK Builder Floor",
    price: "₹ 80.00 Lakh",
    location: "Sector 57, Gurugram",
    image: "/images/property2.jpg",
    type: "Featured",
    beds: 3,
    baths: 2,
    area: "1900 Sq Ft",
    verified: true,
    amenities: [
      "24×7 Security",
      "Swimming Pool",
      "Gymnasium",
      "Children's Play Area",
      "Club House",
      "Power Backup",
      "Lift",
      "Visitor Parking",
      "Jogging Track",
      "CCTV Surveillance",
      "Landscaped Garden",
      "Rain Water Harvesting",
    ],
  },
  {
    id: 3,
    title: "4 BHK Villa",
    price: "₹ 1.25 Cr",
    location: "DLF Phase 2, Gurugram",
    image: "/images/property3.jpg",
    type: "Featured",
    beds: 4,
    baths: 4,
    area: "3400 Sq Ft",
    verified: true,
    amenities: [
      "24×7 Security",
      "Swimming Pool",
      "Gymnasium",
      "Children's Play Area",
      "Club House",
      "Power Backup",
      "Lift",
      "Visitor Parking",
      "Jogging Track",
      "CCTV Surveillance",
      "Landscaped Garden",
      "Rain Water Harvesting",
    ],
  },
  {
    id: 4,
    title: "Luxury Apartment",
    price: "₹ 2.75 Cr",
    location: "Golf Course Road, Gurugram",
    image: "/images/property4.jpg",
    type: "Featured",
    beds: 3,
    baths: 3,
    area: "2100 Sq Ft",
    verified: true,
    amenities: [
      "24×7 Security",
      "Swimming Pool",
      "Gymnasium",
      "Children's Play Area",
      "Club House",
      "Power Backup",
      "Lift",
      "Visitor Parking",
      "Jogging Track",
      "CCTV Surveillance",
      "Landscaped Garden",
      "Rain Water Harvesting",
    ],
  },
];
